language: c
sudo: required

before_install:
  - sudo apt-get install gfortran
  - sudo apt-get install lcov

script:
  - cd libRALFit/
  - mkdir build
  - cd build/
  - cmake ..
  - make
  - cd test
  - ./test
  - ./nlls_c_test
  - cd ../../
  - mkdir coverage
  - cd coverage
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - test/test
  - cd ../src
  - cp ../coverage/CMakeFiles/ral_nlls.dir/src/ral_nlls_dtrs_double.f90.gcda ral_nlls_dtrs_double.gcda
  - cp ../coverage/CMakeFiles/ral_nlls.dir/src/ral_nlls_dtrs_double.f90.gcno ral_nlls_dtrs_double.gcno
  - gcov ral_nlls_dtrs_double.f90
  - cp ../coverage/CMakeFiles/ral_nlls.dir/src/ral_nlls_symbols.f90.gcda ral_nlls_symbols.gcda
  - cp ../coverage/CMakeFiles/ral_nlls.dir/src/ral_nlls_symbols.f90.gcno ral_nlls_symbols.gcno
  - gcov ral_nlls_symbols.f90
  - cp ../coverage/CMakeFiles/ral_nlls.dir/src/ral_nlls_internal.f90.gcda ral_nlls_internal.gcda
  - cp ../coverage/CMakeFiles/ral_nlls.dir/src/ral_nlls_internal.f90.gcno ral_nlls_internal.gcno
  - gcov ral_nlls_internal.f90

  
# send data to codecov:
after_success:
  - bash <(curl -s https://codecov.io/bash) -v -X gcov