language: c
sudo: required

before_install:
  - sudo apt-get install gfortran
  - sudo apt-get install lcov

script:
  - ./makebuild.sh
  - ./makecov.sh
  
# send data to codecov:
after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov