language: c
sudo: required

before_install:
  - sudo apt-get install gfortran
  - sudo apt-get install lcov
  - sudo apt-get install libblas-dev
  - sudo apt-get install liblapack-dev
  - sudo apt-get install python-numpy
  
# Install packages
script:
  - ./makebuild.sh
  - ./makecov.sh
  
# send data to codecov:
after_success:
  - bash <(curl -s https://codecov.io/bash)