language: c
sudo: required

before_install:
  - sudo apt-get install gfortran

script:
  - cd libRALFit/
  - mkdir build
  - cd build/
  - cmake ..
  - make
  - cd test
  - ./test
  - ./nlls_c_test
  
# send data to codecov:
after_success:
  - bash <(curl -s https://codecov.io/bash)